language: ruby
cache: bundler
rvm:
  - 2.2.4
install:
  - bundle install
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rake db:create db:migrate RAILS_ENV=test
script:
  - RAILS_ENV=test bundle exec rake test
services:
  - redis-server

